$ErrorActionPreference = 'Stop'
Write-Host 'DEPRECATED: PmAiRpaLuncher.exe の単体配布は廃止しました。' -ForegroundColor Yellow
Write-Host '  操作者 PC: 配台 PMD.exe → リモートデスクトップタブ' -ForegroundColor Yellow
Write-Host '  接続先 PC: PmAiRdpRemoteLauncher.exe（scripts/build-rdp-remote-launcher.ps1）' -ForegroundColor Yellow
exit 1

# Remote Desktop RPA Launcher - Windows portable bundle (jpackage + bundled JVM).
#
# Prerequisites:
#   - Run on Windows (OpenJFX win classifier).
#   - JDK with jpackage (Temurin zip -> build_cache, or -JdkRuntimeImage).
#   - Optional: dotnet SDK for PmAiRdpRemoteLauncher.exe (scripts/build-rdp-remote-launcher.ps1).
#
# Usage (from code_java):
#   .\package_rdp_launcher_app.ps1
#   .\package_rdp_launcher_app.ps1 -PackageType exe
#   .\package_rdp_launcher_app.ps1 -SkipCsLauncherBuild
#   .\package_rdp_launcher_app.ps1 -SkipJdkPrepare -SkipJavaFxPrepare
#
# Output:
#   rpa_luncher_release\PmAiRpaLuncher\PmAiRpaLuncher.exe  (double-click to start)
#   rpa_luncher_release\PmAiRpaLuncher_portable.zip
#   dist\PmAiRpaLuncher\  (same layout as release folder)

# UTF-8 BOM: Windows PowerShell 5.1
[CmdletBinding()]
param(
    [ValidateSet('app-image', 'exe', 'msi')]
    [string]$PackageType = 'app-image',

    [switch]$WinConsole,

    [switch]$SkipJdkPrepare,

    [switch]$SkipJavaFxPrepare,

    [switch]$SkipCsLauncherBuild,

    [switch]$SkipZip,

    [switch]$SkipCanonicalDeploy,

    [string]$CanonicalDeployDir = '',

    [string]$JdkRuntimeImage = '',

    [string]$JpackageDest = ''
)

$ErrorActionPreference = 'Stop'

$Root = if ($PSScriptRoot) { $PSScriptRoot } else { Get-Location }
Set-Location $Root

$WorkspaceRoot = (Resolve-Path -LiteralPath (Join-Path $Root '..')).Path
$ReleaseDirName = 'rpa_luncher_release'
$ReleaseRoot = Join-Path $WorkspaceRoot $ReleaseDirName

. (Join-Path $Root 'package_jpackage_common.ps1')

function Get-DefaultRdpCanonicalDeployUnc {
    # UTF-8 bytes for 共有フォルダ\掲示板\rpa_luncher (WSL→powershell.exe で ps1 内日本語が化ける対策)
    $utf8 = [System.Text.Encoding]::UTF8
    $shareSuffix = $utf8.GetString([byte[]](
            0xE5, 0x85, 0xB1, 0xE6, 0x9C, 0x89,
            0xE3, 0x83, 0x95, 0xE3, 0x82, 0xA9, 0xE3, 0x83, 0xAB, 0xE3, 0x83, 0x80,
            0x5C,
            0xE6, 0x8E, 0xB2, 0xE7, 0xA4, 0xBA, 0xE6, 0x9D, 0xBF,
            0x5C,
            0x72, 0x70, 0x61, 0x5F, 0x6C, 0x75, 0x6E, 0x63, 0x68, 0x65, 0x72))
    return '\\192.168.0.101\' + $shareSuffix
}

function Resolve-RdpCanonicalDeployDir {
    param([string]$Override)
    if (-not [string]::IsNullOrWhiteSpace($Override)) {
        return $Override.Trim().TrimEnd('\', '/')
    }
    $fromEnv = $env:PM_AI_RDP_CANONICAL_DEPLOY_DIR
    if (-not [string]::IsNullOrWhiteSpace($fromEnv)) {
        return $fromEnv.Trim().TrimEnd('\', '/')
    }
    return Get-DefaultRdpCanonicalDeployUnc
}

function Build-RdpLauncherPortableBatContent {
    param(
        [string]$JavafxVersion,
        [string]$JvmInitial,
        [string]$JvmMax,
        [string]$LauncherExeBaseName = 'PmAiRpaLuncher'
    )
    $jv = ($JavafxVersion -replace '[\r\n\t]', '').Trim()
    if ([string]::IsNullOrWhiteSpace($jv)) {
        $jv = '26.0.1'
    }
    $xms = Normalize-JvmHeapToken $JvmInitial
    $xmx = Normalize-JvmHeapToken $JvmMax
    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add('@echo off')
    $lines.Add('rem ASCII-only. Generated by package_rdp_launcher_app.ps1')
    $lines.Add('rem Do not paste into PowerShell; run: .\launch-pm-ai-rdp-launcher.bat')
    $lines.Add('setlocal EnableExtensions EnableDelayedExpansion')
    $lines.Add('')
    $lines.Add('set "ROOT=%~dp0"')
    $lines.Add('if "%ROOT:~-1%"=="\" set "ROOT=%ROOT:~0,-1%"')
    $lines.Add('cd /d "%ROOT%"')
    $lines.Add('')
    $lines.Add('if not exist "%ROOT%\app" (')
    $lines.Add('    echo [ERROR] Missing app folder. Put this bat next to ' + $LauncherExeBaseName + '.exe / app / runtime.')
    $lines.Add('    echo Current: "%ROOT%"')
    $lines.Add('pause')
    $lines.Add('    exit /b 1')
    $lines.Add(')')
    $lines.Add('')
    $lines.Add('set "JAVA_EXE=%ROOT%\runtime\bin\java.exe"')
    $lines.Add('if exist "%JAVA_EXE%" goto :have_java')
    $lines.Add('if defined JAVA_HOME (')
    $lines.Add('    if exist "%JAVA_HOME%\bin\java.exe" (')
    $lines.Add('        set "JAVA_EXE=%JAVA_HOME%\bin\java.exe"')
    $lines.Add('        echo [WARN] Using JAVA_HOME java.exe (bundled runtime missing).')
    $lines.Add('        goto :have_java')
    $lines.Add('    )')
    $lines.Add(')')
    $lines.Add('echo [ERROR] Java not found: "%ROOT%\runtime\bin\java.exe"')
    $lines.Add('pause')
    $lines.Add('exit /b 1')
    $lines.Add('')
    $lines.Add(':have_java')
    $lines.Add('set "PM_AI_JFX_MODPATH=%ROOT%\app\jfx-mod"')
    $compatJvm = '--add-opens=javafx.base/com.sun.javafx.event=ALL-UNNAMED --add-opens=javafx.controls/javafx.scene.control.skin=ALL-UNNAMED --add-opens=javafx.controls/com.sun.javafx.scene.control.behavior=ALL-UNNAMED --add-exports=javafx.controls/com.sun.javafx.scene.control.behavior=ALL-UNNAMED --enable-native-access=javafx.graphics'
    $javaLine = '"%JAVA_EXE%" -Dfile.encoding=UTF-8 -Xms' + $xms + ' -Xmx' + $xmx + ' -Dprism.order=sw ' + $compatJvm + ' --module-path "!PM_AI_JFX_MODPATH!" --add-modules javafx.controls,javafx.fxml,javafx.graphics,javafx.base,javafx.media,javafx.swing -classpath "%ROOT%\app\*" jp.co.pm.ai.desktop.RemoteDesktopFxApp %*'
    $lines.Add($javaLine)
    $lines.Add('set EXITCODE=!ERRORLEVEL!')
    $lines.Add('if !EXITCODE! neq 0 (')
    $lines.Add('    echo.')
    $lines.Add('    echo [Exit !EXITCODE!] Logs: !USERPROFILE!\.pm-ai-desktop-rdp\')
    $lines.Add(')')
    $lines.Add('exit /b !EXITCODE!')
    $lines.Add('')
    return ($lines.ToArray() -join "`r`n")
}

function Copy-RdpLauncherDeploySeed {
    param(
        [string]$DistAppRoot,
        [string]$ClassesRdpLauncherDir,
        [string]$ResourcesRdpLauncherDir
    )
    $seed = Join-Path $DistAppRoot 'launcher-deploy-seed'
    if (Test-Path -LiteralPath $seed) {
        Remove-Item -Recurse -Force $seed
    }
    New-Item -ItemType Directory -Path $seed -Force | Out-Null
    $sourceDir = $ClassesRdpLauncherDir
    if (-not (Test-Path -LiteralPath $sourceDir)) {
        $sourceDir = $ResourcesRdpLauncherDir
    }
    if (-not (Test-Path -LiteralPath $sourceDir)) {
        Write-Warning "RDP C# launcher resources missing (build with dotnet or run without -SkipCsLauncherBuild)"
        return
    }
    Copy-Item -Path (Join-Path $sourceDir '*') -Destination $seed -Force
    $exeInSeed = Join-Path $seed 'PmAiRdpRemoteLauncher.exe'
    if (-not (Test-Path -LiteralPath $exeInSeed)) {
        Write-Warning "launcher-deploy-seed has no PmAiRdpRemoteLauncher.exe — run scripts/build-rdp-remote-launcher.ps1"
    }
    Write-Host "launcher-deploy-seed: $seed" -ForegroundColor DarkGray
}

<#
  jpackage native exe fails to expand $APPDIR on Unicode install paths (Japanese folder names).
  Replace with C# stub that resolves exe directory and spawns runtime\bin\java.exe (same as .bat).
#>
function Install-RdpDesktopLauncherExe {
    param(
        [Parameter(Mandatory)][string]$BundleRoot,
        [Parameter(Mandatory)][string]$AppExeBaseName,
        [Parameter(Mandatory)][string]$WorkspaceRootPath
    )
    $targetExe = Join-Path $BundleRoot ($AppExeBaseName + '.exe')
    $stubExe = Join-Path $BundleRoot ($AppExeBaseName + '-jpackage-stub.exe')
    $resourceExe = Join-Path $WorkspaceRootPath 'code_java/src/main/resources/jp/co/pm/ai/desktop/rdp-launcher/PmAiRpaLuncher.exe'
    $publishExe = Join-Path $WorkspaceRootPath 'tools/pm-ai-rdp-desktop-launcher/bin/Release/net8.0-windows/win-x64/publish/PmAiRdpDesktopLauncher.exe'
    $srcExe = $null
    if (Test-Path -LiteralPath $resourceExe) {
        $srcExe = $resourceExe
    }
    elseif (Test-Path -LiteralPath $publishExe) {
        $srcExe = $publishExe
    }
    if (-not $srcExe) {
        throw @"
Desktop launcher stub missing. Build with:
  scripts/build-rdp-desktop-launcher.ps1
or run package without -SkipCsLauncherBuild.
Expected: $resourceExe
"@
    }
    if (Test-Path -LiteralPath $targetExe) {
        if (Test-Path -LiteralPath $stubExe) {
            Remove-Item -LiteralPath $stubExe -Force -ErrorAction SilentlyContinue
        }
        Move-Item -LiteralPath $targetExe -Destination $stubExe -Force
        Write-Host "Renamed jpackage stub: $stubExe" -ForegroundColor DarkGray
    }
    Copy-Item -LiteralPath $srcExe -Destination $targetExe -Force
    Write-Host "Installed Unicode-safe desktop launcher: $targetExe" -ForegroundColor DarkGray
}

function Test-RdpPortableLauncherExe {
    param(
        [Parameter(Mandatory)][string]$BundleRoot,
        [Parameter(Mandatory)][string]$AppExeBaseName
    )
    $mainExe = Join-Path $BundleRoot ($AppExeBaseName + '.exe')
    if (-not (Test-Path -LiteralPath $mainExe)) {
        throw "Portable launcher exe missing: $mainExe (jpackage app-image should create it next to app\ and runtime\)."
    }
    $diagBin = Join-Path $BundleRoot 'runtime\bin'
    $bundledJavaExe = Join-Path $diagBin 'java.exe'
    $exeInBin = @()
    if (Test-Path -LiteralPath $diagBin) {
        $exeInBin = @(Get-ChildItem -LiteralPath $diagBin -Filter '*.exe' -File -ErrorAction SilentlyContinue)
    }
    $hasJavaExe = Test-Path -LiteralPath $bundledJavaExe
    if (-not $hasJavaExe -and $exeInBin.Count -gt 0) {
        $hasJavaExe = [bool]($exeInBin | Where-Object { $_.Name -ieq 'java.exe' })
    }
    if (-not $hasJavaExe) {
        Write-Warning @"
Bundled JVM launcher missing: $bundledJavaExe
Common causes: Windows Defender removed java.exe; non-ASCII repo path (use -JpackageDest); stale dist.
Portable start uses $AppExeBaseName.exe — fix runtime before distributing.
"@
    }
    return $mainExe
}

function Publish-RdpPortableBundleToRelease {
    param(
        [Parameter(Mandatory)][string]$DistAppRoot,
        [Parameter(Mandatory)][string]$ReleaseRootPath,
        [Parameter(Mandatory)][string]$AppFolderName
    )
    New-Item -ItemType Directory -Path $ReleaseRootPath -Force | Out-Null
    $releaseBundle = Join-Path $ReleaseRootPath $AppFolderName
    $publishTarget = $releaseBundle
    if (Test-Path -LiteralPath $releaseBundle) {
        $removed = Remove-DirectoryWithRetry -Path $releaseBundle -CloseHint 'close PmAiRpaLuncher.exe / Explorer on release folder'
        if (-not $removed) {
            Write-Host "--- Release folder locked; mirror with robocopy: $releaseBundle ---" -ForegroundColor Cyan
            $roboExit = Mirror-DirectoryWithRobocopy -Source $DistAppRoot -Destination $releaseBundle
            if ($roboExit -lt 8) {
                Write-Host "Release folder updated (robocopy): $releaseBundle" -ForegroundColor Green
                return (Resolve-Path -LiteralPath $releaseBundle).Path
            }
            $publishTarget = Join-Path $ReleaseRootPath ($AppFolderName + '-build-' + [Guid]::NewGuid().ToString('N').Substring(0, 12))
            Write-Warning "Release folder still locked; publishing alternate bundle: $publishTarget"
        }
    }
    if ($publishTarget -ne $releaseBundle -or -not (Test-Path -LiteralPath $releaseBundle)) {
        Copy-Item -Recurse -Force -LiteralPath $DistAppRoot -Destination $publishTarget
    }
    return (Resolve-Path -LiteralPath $publishTarget).Path
}

function Read-AppVersionFromRepo {
    param(
        [string]$WorkspaceRootPath,
        [string]$FallbackVersion
    )
    $versionTxt = Join-Path $WorkspaceRootPath 'version.txt'
    $appVer = $FallbackVersion -replace '-SNAPSHOT$', '.0'
    if (Test-Path -LiteralPath $versionTxt) {
        $rawTxt = (Get-Content -LiteralPath $versionTxt -TotalCount 1 -Encoding UTF8).Trim()
        if (-not [string]::IsNullOrWhiteSpace($rawTxt)) {
            $digits = -join ($rawTxt.ToCharArray() | Where-Object { [char]::IsDigit($_) -or $_ -eq '.' })
            if (-not [string]::IsNullOrWhiteSpace($digits)) {
                $appVer = $digits
                if ($appVer -match '^\d+\.\d+$') {
                    $appVer = "$appVer.0"
                }
            }
        }
    }
    return $appVer
}

$APP_NAME = 'PmAiRpaLuncher'
$MAIN_CLASS = 'jp.co.pm.ai.desktop.RemoteDesktopFxApp'

$POM = Join-Path $Root 'pom.xml'
$pomProps = Read-MavenPomProperties -PomPath $POM
$jvmInitial = '512m'
$jvmMax = $pomProps['jvm.max.heap.rdp']
$prismOrder = $pomProps['javafx.prism.order']
if ([string]::IsNullOrWhiteSpace($jvmMax)) { $jvmMax = '2g' }
if ([string]::IsNullOrWhiteSpace($prismOrder)) { $prismOrder = 'sw' }

$proj = Get-MavenProjectInfo -PomPath $POM
$APP_VERSION = Read-AppVersionFromRepo -WorkspaceRootPath $WorkspaceRoot -FallbackVersion $proj.Version

if (-not $SkipCsLauncherBuild) {
    $csBuild = Join-Path $WorkspaceRoot 'scripts/build-rdp-remote-launcher.ps1'
    if (Test-Path -LiteralPath $csBuild) {
        Write-Host "--- Build PmAiRdpRemoteLauncher.exe (dotnet publish) ---" -ForegroundColor Cyan
        & $csBuild -RepoRoot $WorkspaceRoot
    }
    else {
        Write-Warning "Missing $csBuild — skipping C# remote launcher build."
    }
    $desktopBuild = Join-Path $WorkspaceRoot 'scripts/build-rdp-desktop-launcher.ps1'
    if (Test-Path -LiteralPath $desktopBuild) {
        Write-Host "--- Build PmAiRpaLuncher.exe stub (dotnet publish) ---" -ForegroundColor Cyan
        & $desktopBuild -RepoRoot $WorkspaceRoot
    }
    else {
        Write-Warning "Missing $desktopBuild — skipping desktop launcher stub build."
    }
}

Write-Host "--- Maven package ---" -ForegroundColor Cyan
$mvnw = Join-Path $Root 'mvnw.cmd'
if (-not (Test-Path -LiteralPath $mvnw)) {
    throw "Maven Wrapper not found: $mvnw"
}
& $mvnw @('clean', 'package', '-DskipTests')
if ($LASTEXITCODE -ne 0) {
    Write-Error 'Maven build failed.'
    exit $LASTEXITCODE
}

$packageInput = Join-Path $Root 'package_input_rdp'
Copy-JpackageInputDirectory -RootPath $Root -MainJarName $proj.MainJar -DestPath $packageInput

$cacheRoot = Join-Path $Root 'build_cache'

$javafxVer = Expand-PomPropertyPlaceholder -Raw ([string]$pomProps['javafx.version']) -Props $pomProps
if ([string]::IsNullOrWhiteSpace($javafxVer)) {
    throw 'pom.xml: javafx.version is required.'
}
Sync-JavaFxWindowsRuntimeFromMavenCentral -PackageInputDir $packageInput -JavafxVersion $javafxVer -CacheRoot $cacheRoot -Skip:$SkipJavaFxPrepare
Prepare-JavaFxJpackageModuleDir -AppDir $packageInput -JavafxVersion $javafxVer
Remove-JpackageTestArtifactsFromAppDir -AppDir $packageInput

$jdkRelease = Expand-PomPropertyPlaceholder -Raw ([string]$pomProps['pm.ai.bundle.jdk.windows.release']) -Props $pomProps
if ([string]::IsNullOrWhiteSpace($jdkRelease)) {
    $jdkRelease = Expand-PomPropertyPlaceholder -Raw ([string]$pomProps['maven.compiler.release']) -Props $pomProps
}
$jdkZipUrl = ''
if ($pomProps.ContainsKey('pm.ai.bundle.jdk.windows.zip.url')) {
    $jdkZipUrl = [string]$pomProps['pm.ai.bundle.jdk.windows.zip.url']
}

if (-not [string]::IsNullOrWhiteSpace($JdkRuntimeImage)) {
    $jdkRoot = $JdkRuntimeImage.TrimEnd('\', '/')
}
elseif (-not [string]::IsNullOrWhiteSpace($env:PM_AI_JDK_RUNTIME_IMAGE)) {
    $jdkRoot = $env:PM_AI_JDK_RUNTIME_IMAGE.Trim().TrimEnd('\', '/')
}
else {
    $jdkRoot = [string](Ensure-JdkWindowsEmbedCache -CacheRoot $cacheRoot -JdkRelease $jdkRelease `
            -ZipUrlOverride $jdkZipUrl -Skip:$SkipJdkPrepare)
}

$JPACKAGE = Join-Path $jdkRoot 'bin\jpackage.exe'
if (-not (Test-Path -LiteralPath (Join-Path $jdkRoot 'bin\java.exe'))) {
    throw "JDK folder missing bin\java.exe: $jdkRoot"
}
if (-not (Test-Path -LiteralPath $JPACKAGE)) {
    throw "JDK folder missing bin\jpackage.exe: $jdkRoot"
}

Write-Host "--- jpackage (type=$PackageType) ---" -ForegroundColor Cyan

$distFinal = Join-Path $Root 'dist'
$jpkgDestParent = $distFinal
if (-not [string]::IsNullOrWhiteSpace($JpackageDest)) {
    $jpkgDestParent = $JpackageDest.TrimEnd('\', '/')
}
elseif (-not [string]::IsNullOrWhiteSpace($env:PM_AI_JPACKAGE_DEST)) {
    $jpkgDestParent = $env:PM_AI_JPACKAGE_DEST.Trim().TrimEnd('\', '/')
}
elseif ($Root -match '[^\x00-\x7F]') {
    $jpkgDestParent = Join-Path $env:TEMP ("pm-ai-rdp-jpackage-" + [Guid]::NewGuid().ToString('N'))
    Write-Host "Non-ASCII path: staging jpackage --dest to: $jpkgDestParent" -ForegroundColor Cyan
}
$usedStaging = ($jpkgDestParent -ne $distFinal)

$destAppPath = Join-Path $distFinal $APP_NAME
if (Test-Path -LiteralPath $destAppPath) {
    $distRemoved = Remove-DirectoryWithRetry -Path $destAppPath -CloseHint 'close PmAiRpaLuncher.exe / Explorer on code_java\dist'
    if (-not $distRemoved) {
        $destAppPath = Join-Path $distFinal ($APP_NAME + '-build-' + [Guid]::NewGuid().ToString('N').Substring(0, 12))
        Write-Warning "dist\$APP_NAME is locked; jpackage output will use: $destAppPath"
    }
}
if ($usedStaging -and (Test-Path -LiteralPath $jpkgDestParent)) {
    Remove-Item -Recurse -Force -LiteralPath $jpkgDestParent -ErrorAction SilentlyContinue
}
New-Item -ItemType Directory -Path $jpkgDestParent -Force | Out-Null

$jvForJpkg = ($javafxVer -replace '[\r\n\t]', '').Trim()
$javaFxModulePathOpts = New-JavaFxJpackageModulePathJavaOptions -JavafxVersion $jvForJpkg

$javaOpts = @(
    '-Dfile.encoding=UTF-8',
    "-Xms$jvmInitial",
    "-Xmx$jvmMax",
    "-Dprism.order=$prismOrder"
) + $javaFxModulePathOpts + @(
    '--add-modules=javafx.controls,javafx.fxml,javafx.graphics,javafx.base,javafx.media,javafx.swing',
    '--add-opens=javafx.base/com.sun.javafx.event=ALL-UNNAMED',
    '--add-opens=javafx.controls/javafx.scene.control.skin=ALL-UNNAMED',
    '--add-opens=javafx.controls/com.sun.javafx.scene.control.behavior=ALL-UNNAMED',
    '--add-exports=javafx.controls/com.sun.javafx.scene.control.behavior=ALL-UNNAMED',
    '--enable-native-access=javafx.graphics'
)

$jpkgArgs = [System.Collections.Generic.List[string]]::new()
$jpkgArgs.Add('--type'); $jpkgArgs.Add($PackageType)
$jpkgArgs.Add('--input'); $jpkgArgs.Add($packageInput)
$jpkgArgs.Add('--runtime-image'); $jpkgArgs.Add($jdkRoot)
$jpkgArgs.Add('--dest'); $jpkgArgs.Add($jpkgDestParent)
$jpkgArgs.Add('--name'); $jpkgArgs.Add($APP_NAME)
$jpkgArgs.Add('--main-jar'); $jpkgArgs.Add($proj.MainJar)
$jpkgArgs.Add('--main-class'); $jpkgArgs.Add($MAIN_CLASS)
$jpkgArgs.Add('--app-version'); $jpkgArgs.Add($APP_VERSION)
$jpkgArgs.Add('--vendor'); $jpkgArgs.Add('jp.co.pm.ai')
$jpkgArgs.Add('--description'); $jpkgArgs.Add('Remote Desktop RPA Launcher (JavaFX)')
foreach ($opt in $javaOpts) {
    $jpkgArgs.Add('--java-options'); $jpkgArgs.Add($opt)
}
if ($WinConsole) { $jpkgArgs.Add('--win-console') }
if ($PackageType -eq 'exe' -or $PackageType -eq 'msi') {
    $jpkgArgs.Add('--win-shortcut'); $jpkgArgs.Add('--win-menu'); $jpkgArgs.Add('--win-dir-chooser')
}

& $JPACKAGE @($jpkgArgs.ToArray())
if ($LASTEXITCODE -ne 0) {
    Write-Error 'jpackage failed.'
    exit $LASTEXITCODE
}

if ($usedStaging) {
    $staged = Join-Path $jpkgDestParent $APP_NAME
    if (-not (Test-Path -LiteralPath $staged)) {
        throw "jpackage staging output missing: $staged"
    }
    New-Item -ItemType Directory -Path $distFinal -Force | Out-Null
    Copy-Item -Recurse -Force -LiteralPath $staged -Destination $destAppPath
    Remove-Item -Recurse -Force -LiteralPath $jpkgDestParent -ErrorAction SilentlyContinue
}

$distRoot = $destAppPath
$rdpAppDir = Join-Path $distRoot 'app'
Prepare-JavaFxJpackageModuleDir -AppDir $rdpAppDir -JavafxVersion $jvForJpkg
Remove-JpackageTestArtifactsFromAppDir -AppDir $rdpAppDir
$rdpCfgPath = Join-Path $rdpAppDir "$APP_NAME.cfg"
if (Repair-JpackageAppCfgModulePath -CfgFilePath $rdpCfgPath) {
    Write-Host "Repaired legacy jpackage cfg module-path: $rdpCfgPath" -ForegroundColor DarkGray
}
if (Rewrite-RdpLauncherJpackageCfgForExe -CfgFilePath $rdpCfgPath) {
    Write-Host "Rewrote jpackage cfg for exe (classpath wildcard + jfx-mod): $rdpCfgPath" -ForegroundColor DarkGray
}

Install-RdpDesktopLauncherExe -BundleRoot $distRoot -AppExeBaseName $APP_NAME -WorkspaceRootPath $WorkspaceRoot

if ($PackageType -ne 'app-image') {
    Write-Warning "PackageType=$PackageType creates an installer, not a portable folder launcher. For double-click exe + app\runtime, use -PackageType app-image (default)."
}

$classesRdp = Join-Path $Root 'target/classes/jp/co/pm/ai/desktop/rdp-launcher'
$resourcesRdp = Join-Path $Root 'src/main/resources/jp/co/pm/ai/desktop/rdp-launcher'
Copy-RdpLauncherDeploySeed -DistAppRoot $distRoot -ClassesRdpLauncherDir $classesRdp -ResourcesRdpLauncherDir $resourcesRdp

$versionDst = Join-Path $distRoot 'version.txt'
Copy-Item -LiteralPath (Join-Path $WorkspaceRoot 'version.txt') -Destination $versionDst -Force -ErrorAction SilentlyContinue

$readme = Join-Path $distRoot 'README_PORTABLE_RDP.txt'
$canonicalDeployUncForDocs = Resolve-RdpCanonicalDeployDir -Override $CanonicalDeployDir
@(
    'Portable RPA Launcher (PmAiRpaLuncher). Separate from dispatch PMD.exe.',
    'Generated by package_rdp_launcher_app.ps1.',
    '',
    'Start (recommended):',
    '  Double-click PmAiRpaLuncher.exe in this folder.',
    '  Do not move the exe alone — keep app\, runtime\, and the exe in the same folder.',
    '',
    'Layout:',
    '  PmAiRpaLuncher.exe   - main launcher (Unicode-safe C# stub -> bundled JVM)',
    '  PmAiRpaLuncher-jpackage-stub.exe - unused jpackage native launcher (Unicode paths)',
    '  runtime\             - bundled JVM',
    '  app\                 - application jars + JavaFX win jars',
    '  launch-pm-ai-rpa-luncher.bat - fallback if exe fails (AV blocked runtime\bin\java.exe)',
    '  launcher-deploy-seed\ - copy to shared folder (PM_AI_RDP_LAUNCHER_DEPLOY_DIR)',
    '    PmAiRdpRemoteLauncher.exe, profiles JSON, version file',
    '',
    'Per-user settings (PC local): %USERPROFILE%\.pm-ai-desktop-rdp\ (session-state, last operator)',
    'Shared DATA (default): \\\\192.168.0.101\\共有フォルダ\\掲示板\\rpa_luncher\\DATA',
    '  RAP設定.ini, operator users bin — see User Administrator tab.',
    'Launcher deploy folder (remote exe): PM_AI_RDP_LAUNCHER_DEPLOY_DIR = rpa_luncher (not DATA).',
    'Auto-update canonical (default PM_AI_RDP_PORTABLE_BUNDLE_SOURCE_DIR):',
    "  $canonicalDeployUncForDocs",
    '  (version.txt + PmAiRpaLuncher_version_upgrade.zip + build-manifest.json)',
    ''
) | Set-Content -LiteralPath $readme -Encoding UTF8

$batDst = Join-Path $distRoot 'launch-pm-ai-rpa-luncher.bat'
$batBody = Build-RdpLauncherPortableBatContent -JavafxVersion $javafxVer -JvmInitial $jvmInitial -JvmMax $jvmMax -LauncherExeBaseName $APP_NAME
[System.IO.File]::WriteAllText($batDst, $batBody, [System.Text.UTF8Encoding]::new($false))

$applyScriptSrc = Join-Path $WorkspaceRoot 'scripts/rdp-apply-portable-update.ps1'
if (Test-Path -LiteralPath $applyScriptSrc) {
    Copy-Item -LiteralPath $applyScriptSrc -Destination (Join-Path $distRoot 'rdp-apply-portable-update.ps1') -Force
    Write-Host "Portable update script: rdp-apply-portable-update.ps1" -ForegroundColor DarkGray
}

$mainExePath = Test-RdpPortableLauncherExe -BundleRoot $distRoot -AppExeBaseName $APP_NAME
Write-Host "Portable launcher exe verified: $mainExePath" -ForegroundColor DarkGray

$releaseBundlePath = Publish-RdpPortableBundleToRelease -DistAppRoot $distRoot -ReleaseRootPath $ReleaseRoot -AppFolderName $APP_NAME
$releaseExePath = Join-Path $releaseBundlePath ($APP_NAME + '.exe')
Write-Host "--- Published runnable portable bundle: $releaseBundlePath ---" -ForegroundColor Cyan
Write-Host "Start from exe: $releaseExePath" -ForegroundColor Green

Write-Host "--- Done ---" -ForegroundColor Green
Write-Host "Portable app: $mainExePath"
Write-Host "Release exe:  $releaseExePath"
Write-Host "Deploy seed:  $(Join-Path $distRoot 'launcher-deploy-seed')"

$upgradeZipName = 'PmAiRpaLuncher_version_upgrade.zip'
$upgradeZipPath = Join-Path $ReleaseRoot $upgradeZipName

if (-not $SkipZip) {
    New-Item -ItemType Directory -Path $ReleaseRoot -Force | Out-Null
    $zipPortable = Join-Path $ReleaseRoot 'PmAiRpaLuncher_portable.zip'
    if (Test-Path -LiteralPath $zipPortable) {
        Remove-Item -Force -LiteralPath $zipPortable
    }
    Write-Host "--- ZIP portable: $zipPortable ---" -ForegroundColor Cyan
    Compress-Archive -LiteralPath $distRoot -DestinationPath $zipPortable -CompressionLevel Fastest -Force
    Write-Host "Portable ZIP: $zipPortable" -ForegroundColor Green

    if (Test-Path -LiteralPath $upgradeZipPath) {
        Remove-Item -Force -LiteralPath $upgradeZipPath
    }
    Write-Host "--- ZIP version upgrade: $upgradeZipPath ---" -ForegroundColor Cyan
    Compress-Archive -LiteralPath $distRoot -DestinationPath $upgradeZipPath -CompressionLevel Fastest -Force
    Write-Host "Version upgrade ZIP: $upgradeZipPath" -ForegroundColor Green

    $releaseVersionTxt = Join-Path $ReleaseRoot 'version.txt'
    Copy-Item -LiteralPath (Join-Path $WorkspaceRoot 'version.txt') -Destination $releaseVersionTxt -Force -ErrorAction SilentlyContinue

    $desktopJar = Get-ChildItem -LiteralPath (Join-Path $distRoot 'app') -Filter 'production-control-desktop*.jar' -File -ErrorAction SilentlyContinue |
        Select-Object -First 1
    if ($desktopJar) {
        $sha = (Get-FileHash -LiteralPath $desktopJar.FullName -Algorithm SHA256).Hash
        $verLine = if (Test-Path -LiteralPath $releaseVersionTxt) {
            (Get-Content -LiteralPath $releaseVersionTxt -TotalCount 1 -Encoding UTF8).Trim()
        } else { $APP_VERSION }
        $manifestObj = [ordered]@{
            version            = $verLine
            desktopJarFileName = $desktopJar.Name
            desktopJarSize     = $desktopJar.Length
            desktopJarSha256   = $sha
        }
        $manifestPath = Join-Path $ReleaseRoot 'build-manifest.json'
        $manifestObj | ConvertTo-Json | Set-Content -LiteralPath $manifestPath -Encoding utf8
        Write-Host "build-manifest.json: $manifestPath" -ForegroundColor DarkGray
    }

    if (-not $SkipCanonicalDeploy) {
        $canon = Resolve-RdpCanonicalDeployDir -Override $CanonicalDeployDir
        if ([string]::IsNullOrWhiteSpace($canon)) {
            Write-Warning 'CanonicalDeployDir is empty; skip deploy to network canonical folder.'
        }
        else {
            Write-Host "--- Deploy release artifacts to canonical UNC: $canon ---" -ForegroundColor Cyan
            try {
                New-Item -ItemType Directory -Path $canon -Force -ErrorAction Stop | Out-Null
                foreach ($artifact in @(
                        $zipPortable,
                        $upgradeZipPath,
                        $releaseVersionTxt,
                        (Join-Path $ReleaseRoot 'build-manifest.json'))) {
                    if (Test-Path -LiteralPath $artifact) {
                        Copy-Item -LiteralPath $artifact -Destination (Join-Path $canon (Split-Path -Leaf $artifact)) -Force -ErrorAction Stop
                        Write-Host "  -> $(Split-Path -Leaf $artifact)" -ForegroundColor DarkGray
                    }
                }
                Write-Host "Canonical deploy done: $canon" -ForegroundColor Green
            }
            catch {
                Write-Warning "Canonical deploy failed: $($_.Exception.Message)"
                Write-Warning "Local release is ready under $ReleaseRoot. Offline/WSL: use -SkipCanonicalDeploy or copy manually to the share."
            }
        }
    }
}
